import type { ThingInput } from "../types";

export const categoriesData = [
  { id: "cars", name: "Cars & Road Vehicles", description: "From daily commuters to monster machines, the vehicles that rule the road.", sort_order: 15 },
  { id: "ships", name: "Ships & Boats", description: "Vessels that traverse oceans, rivers, and lakes, from tiny kayaks to colossal carriers.", sort_order: 16 },
  { id: "trains", name: "Trains & Rail", description: "Rail-bound machines that haul passengers and freight at remarkable speeds across continents.", sort_order: 17 },
];

export const thingsData: ThingInput[] = [
  // ── Cars & Road Vehicles ─────────────────────────────────────────────────

  {
    slug: "toyota-corolla",
    name: "Toyota Corolla",
    subtitle: "The best-selling car nameplate in history",
    category_id: "cars",
    description:
      "With over 50 million units sold since 1966, the Toyota Corolla is the best-selling car nameplate of all time. It earned its reputation through relentless reliability and an almost supernatural ability to keep running no matter what. If cockroaches survive the apocalypse, they will probably be driving Corollas.",
    search_terms: "toyota|corolla|sedan|commuter|reliable car",
    featured: 1,
    measurements: [
      { dimension: "length", label: "Overall length", value: 4.63, si_unit: "m" },
      { dimension: "length", label: "Width", value: 1.78, si_unit: "m" },
      { dimension: "length", label: "Height", value: 1.44, si_unit: "m" },
      { dimension: "mass", label: "Curb weight", value: 1300, si_unit: "kg" },
      { dimension: "speed", label: "Top speed", value: 50, si_unit: "m/s", note: "About 180 km/h" },
      { dimension: "power", label: "Engine power", value: 103000, si_unit: "W", note: "Approximately 138 hp" },
      { dimension: "volume", label: "Fuel tank capacity", value: 0.05, si_unit: "m³", note: "50 liters" },
      { dimension: "length", label: "Wheelbase", value: 2.7, si_unit: "m" },
    ],
  },
  {
    slug: "school-bus",
    name: "School Bus",
    subtitle: "The unmistakable yellow icon of American childhood",
    category_id: "cars",
    description:
      "The American school bus is one of the most recognizable vehicles on the planet, painted in a shade officially called National School Bus Glossy Yellow. Roughly 480,000 of them transport 26 million students every day in the United States alone. They are engineered to be the safest vehicles on the road, which is why they have no seatbelts and are built like rolling tanks.",
    search_terms: "school bus|yellow bus|student transport|bus",
    featured: 0,
    measurements: [
      { dimension: "length", label: "Overall length", value: 10.7, si_unit: "m", note: "Type C conventional, 72-passenger" },
      { dimension: "length", label: "Height", value: 3.0, si_unit: "m" },
      { dimension: "length", label: "Width", value: 2.44, si_unit: "m" },
      { dimension: "mass", label: "Gross vehicle weight", value: 10000, si_unit: "kg" },
      { dimension: "speed", label: "Typical top speed", value: 27, si_unit: "m/s", note: "About 97 km/h, often governed" },
      { dimension: "volume", label: "Fuel tank capacity", value: 0.114, si_unit: "m³", note: "About 114 liters" },
      { dimension: "length", label: "Wheelbase", value: 6.3, si_unit: "m" },
    ],
  },
  {
    slug: "tesla-cybertruck",
    name: "Tesla Cybertruck",
    subtitle: "The angular stainless-steel pickup from the future",
    category_id: "cars",
    description:
      "Unveiled in 2019 and finally delivered in late 2023, the Tesla Cybertruck looks like it was designed in a geometry class using only a ruler. Its exoskeleton is made from ultra-hard 30X cold-rolled stainless steel, the same alloy SpaceX uses for Starship. Whether you find it beautiful or baffling, nobody has ever confused one for a Honda.",
    search_terms: "tesla|cybertruck|electric truck|ev|pickup|stainless steel",
    featured: 1,
    measurements: [
      { dimension: "length", label: "Overall length", value: 5.68, si_unit: "m" },
      { dimension: "length", label: "Width", value: 2.2, si_unit: "m" },
      { dimension: "length", label: "Height", value: 1.79, si_unit: "m" },
      { dimension: "mass", label: "Curb weight", value: 3100, si_unit: "kg", note: "Cyberbeast tri-motor variant" },
      { dimension: "speed", label: "Top speed", value: 56, si_unit: "m/s", note: "About 200 km/h" },
      { dimension: "power", label: "Peak motor power", value: 600000, si_unit: "W", note: "Tri-motor Cyberbeast, approximately 845 hp" },
      { dimension: "energy", label: "Battery capacity", value: 360000000, si_unit: "J", note: "About 100 kWh" },
      { dimension: "length", label: "Bed length", value: 1.83, si_unit: "m" },
    ],
  },
  {
    slug: "monster-truck-bigfoot",
    name: "Monster Truck (Bigfoot)",
    subtitle: "The original monster truck that started it all",
    category_id: "cars",
    description:
      "Bigfoot 1 was built by Bob Chandler in 1975 and became the first truck to crush cars under its enormous tires, spawning an entire motorsport genre. Modern iterations of Bigfoot run on tires originally designed for the U.S. Army and produce enough horsepower to make a Lamborghini blush. The truck exists to remind us that sometimes the best engineering question is simply 'what if we made it bigger?'",
    search_terms: "bigfoot|monster truck|truck rally|car crusher|giant truck",
    featured: 0,
    measurements: [
      { dimension: "length", label: "Height", value: 4.7, si_unit: "m" },
      { dimension: "mass", label: "Vehicle mass", value: 5400, si_unit: "kg" },
      { dimension: "length", label: "Tire diameter", value: 1.68, si_unit: "m", note: "66-inch tires" },
      { dimension: "power", label: "Engine power", value: 1118550, si_unit: "W", note: "Approximately 1,500 hp" },
      { dimension: "length", label: "Overall length", value: 3.8, si_unit: "m" },
      { dimension: "length", label: "Width", value: 3.66, si_unit: "m" },
      { dimension: "length", label: "Tire width", value: 1.1, si_unit: "m", note: "43-inch wide tires" },
    ],
  },
  {
    slug: "formula-1-car",
    name: "Formula 1 Car",
    subtitle: "The fastest circuit-racing machines on Earth",
    category_id: "cars",
    description:
      "A modern Formula 1 car is an aerodynamic sculpture made of carbon fiber that generates more downforce than its own weight, meaning it could theoretically drive upside down on a ceiling. The hybrid power unit combines a turbocharged V6 with energy recovery systems to produce around 1,000 horsepower while meeting fuel flow limits. Brakes can decelerate the car at over 6g, which is roughly the force of having a baby elephant sitting on your chest.",
    search_terms: "f1|formula one|formula 1|grand prix|racing car|open wheel",
    featured: 1,
    measurements: [
      { dimension: "length", label: "Overall length", value: 5.6, si_unit: "m" },
      { dimension: "length", label: "Width", value: 2.0, si_unit: "m" },
      { dimension: "mass", label: "Minimum weight with driver", value: 798, si_unit: "kg", note: "2024 FIA regulations" },
      { dimension: "speed", label: "Top speed", value: 97, si_unit: "m/s", note: "About 350 km/h depending on circuit" },
      { dimension: "power", label: "Power unit output", value: 735000, si_unit: "W", note: "About 1,000 hp combined ICE and ERS" },
      { dimension: "force", label: "Peak downforce", value: 25000, si_unit: "N", note: "At high speed; exceeds the car's own weight" },
      { dimension: "length", label: "Wheelbase", value: 3.6, si_unit: "m" },
      { dimension: "volume", label: "Fuel capacity", value: 0.11, si_unit: "m³", note: "Max 110 kg of fuel (~110 liters)" },
    ],
  },
  {
    slug: "london-double-decker-bus",
    name: "London Double-Decker Bus",
    subtitle: "The iconic red symbol of London's streets",
    category_id: "cars",
    description:
      "The red double-decker bus is as much a symbol of London as Big Ben or tea with milk. The modern New Routemaster entered service in 2012 as a diesel-electric hybrid, carrying up to 87 passengers on two decks. British people instinctively use it as a unit of measurement for anything large, which is exactly why it belongs here.",
    search_terms: "double decker|london bus|routemaster|red bus|british bus",
    featured: 0,
    measurements: [
      { dimension: "length", label: "Overall length", value: 11.0, si_unit: "m" },
      { dimension: "length", label: "Height", value: 4.4, si_unit: "m" },
      { dimension: "length", label: "Width", value: 2.55, si_unit: "m" },
      { dimension: "mass", label: "Gross vehicle weight", value: 12500, si_unit: "kg" },
      { dimension: "speed", label: "Top speed", value: 18, si_unit: "m/s", note: "About 65 km/h" },
      { dimension: "length", label: "Wheelbase", value: 5.87, si_unit: "m" },
    ],
  },

  // ── Aircraft ─────────────────────────────────────────────────────────────

  {
    slug: "sr-71-blackbird",
    name: "SR-71 Blackbird",
    subtitle: "The fastest air-breathing manned aircraft ever built",
    category_id: "aircraft",
    description:
      "The Lockheed SR-71 Blackbird flew so fast that its standard evasive maneuver against missiles was to simply accelerate. Cruising at Mach 3.3, the titanium airframe would expand several inches from thermal heating, and the panels were designed to fit loosely on the ground, meaning it literally leaked fuel until it got hot enough to seal. It set the speed record for a manned air-breathing aircraft in 1976, and nobody has beaten it since.",
    search_terms: "sr71|sr-71|blackbird|lockheed|spy plane|reconnaissance|mach 3",
    featured: 1,
    measurements: [
      { dimension: "length", label: "Overall length", value: 32.7, si_unit: "m" },
      { dimension: "length", label: "Wingspan", value: 16.9, si_unit: "m" },
      { dimension: "mass", label: "Empty mass", value: 30600, si_unit: "kg" },
      { dimension: "speed", label: "Maximum speed", value: 981, si_unit: "m/s", note: "Mach 3.3, about 3,530 km/h" },
      { dimension: "length", label: "Service ceiling", value: 25900, si_unit: "m", note: "About 85,000 feet" },
      { dimension: "temperature", label: "Skin temperature at speed", value: 589, si_unit: "K", note: "About 316 degrees Celsius on the windshield" },
      { dimension: "length", label: "Height", value: 5.64, si_unit: "m" },
      { dimension: "length", label: "Range", value: 5400000, si_unit: "m", note: "5,400 km without refueling" },
    ],
  },
  {
    slug: "wright-flyer",
    name: "Wright Flyer",
    subtitle: "The first powered heavier-than-air flying machine",
    category_id: "aircraft",
    description:
      "On December 17, 1903, at Kitty Hawk, North Carolina, the Wright Flyer became the first powered aircraft to achieve sustained, controlled flight. That first flight covered just 37 meters in 12 seconds, which is less distance than a Boeing 747's wingspan. A piece of the original wing fabric and propeller traveled aboard Apollo 11 to the Moon, making it the most well-traveled piece of muslin in history.",
    search_terms: "wright brothers|wright flyer|kitty hawk|first flight|first airplane",
    featured: 1,
    measurements: [
      { dimension: "length", label: "Wingspan", value: 12.3, si_unit: "m" },
      { dimension: "length", label: "Overall length", value: 6.4, si_unit: "m" },
      { dimension: "mass", label: "Empty mass", value: 274, si_unit: "kg" },
      { dimension: "speed", label: "Airspeed", value: 13.4, si_unit: "m/s", note: "About 48 km/h" },
      { dimension: "time", label: "First flight duration", value: 12, si_unit: "s", note: "December 17, 1903, first of four flights that day" },
      { dimension: "power", label: "Engine power", value: 8950, si_unit: "W", note: "About 12 hp" },
      { dimension: "length", label: "First flight distance", value: 37, si_unit: "m" },
      { dimension: "area", label: "Wing area", value: 47.4, si_unit: "m²" },
    ],
  },
  {
    slug: "cessna-172",
    name: "Cessna 172 Skyhawk",
    subtitle: "The most produced aircraft in aviation history",
    category_id: "aircraft",
    description:
      "With more than 44,000 units built since 1956, the Cessna 172 is the most produced aircraft in history and the backbone of flight training worldwide. Almost every private pilot alive learned to fly in one. It is the Honda Civic of the sky: unglamorous, affordable, and so forgiving of student mistakes that it practically flies itself.",
    search_terms: "cessna|172|skyhawk|trainer|light aircraft|general aviation",
    featured: 0,
    measurements: [
      { dimension: "length", label: "Wingspan", value: 11.0, si_unit: "m" },
      { dimension: "length", label: "Overall length", value: 8.28, si_unit: "m" },
      { dimension: "mass", label: "Empty mass", value: 767, si_unit: "kg" },
      { dimension: "speed", label: "Cruise speed", value: 63, si_unit: "m/s", note: "About 226 km/h" },
      { dimension: "length", label: "Range", value: 1289000, si_unit: "m", note: "1,289 km" },
      { dimension: "length", label: "Service ceiling", value: 4267, si_unit: "m", note: "14,000 feet" },
      { dimension: "length", label: "Height", value: 2.72, si_unit: "m" },
      { dimension: "volume", label: "Fuel capacity", value: 0.212, si_unit: "m³", note: "212 liters (56 US gallons)" },
    ],
  },
  {
    slug: "airbus-a380",
    name: "Airbus A380",
    subtitle: "The world's largest passenger airliner",
    category_id: "aircraft",
    description:
      "The Airbus A380 is the world's largest passenger aircraft, a double-deck, wide-body behemoth that can seat over 800 passengers in an all-economy configuration. Its wingspan is so enormous that airports had to widen taxiways to accommodate it. Production ended in 2021, making it the magnificent white elephant of aviation: too big for most routes, but unforgettable for anyone who has flown on one.",
    search_terms: "airbus|a380|superjumbo|double deck|largest airliner",
    featured: 1,
    measurements: [
      { dimension: "length", label: "Wingspan", value: 79.75, si_unit: "m" },
      { dimension: "length", label: "Fuselage length", value: 72.7, si_unit: "m" },
      { dimension: "length", label: "Height", value: 24.1, si_unit: "m" },
      { dimension: "mass", label: "Operating empty mass", value: 277000, si_unit: "kg" },
      { dimension: "speed", label: "Cruise speed", value: 270, si_unit: "m/s", note: "Mach 0.85, about 972 km/h" },
      { dimension: "volume", label: "Total cabin volume", value: 1570, si_unit: "m³" },
      { dimension: "length", label: "Range", value: 15200000, si_unit: "m", note: "15,200 km" },
      { dimension: "area", label: "Wing area", value: 845, si_unit: "m²" },
    ],
  },
  {
    slug: "apache-helicopter-ah-64",
    name: "Apache Helicopter (AH-64)",
    subtitle: "The U.S. Army's primary attack helicopter",
    category_id: "aircraft",
    description:
      "The Boeing AH-64 Apache is the most advanced and lethal attack helicopter in the world, featuring a nose-mounted sensor suite, a 30mm chain gun that follows the pilot's helmet movements, and the ability to carry a mix of Hellfire missiles and rockets. It can operate in all weather conditions, day or night. The Apache has been in service since 1986 and has seen action in nearly every major U.S. military operation since.",
    search_terms: "apache|ah-64|attack helicopter|gunship|boeing helicopter",
    featured: 0,
    measurements: [
      { dimension: "length", label: "Fuselage length", value: 17.7, si_unit: "m", note: "With rotors turning" },
      { dimension: "mass", label: "Empty mass", value: 5165, si_unit: "kg" },
      { dimension: "speed", label: "Maximum speed", value: 90, si_unit: "m/s", note: "About 324 km/h" },
      { dimension: "length", label: "Main rotor diameter", value: 14.6, si_unit: "m" },
      { dimension: "length", label: "Height", value: 3.87, si_unit: "m" },
      { dimension: "power", label: "Engine power (x2)", value: 2460000, si_unit: "W", note: "Two GE T700 turboshafts, ~1,650 shp each" },
      { dimension: "length", label: "Service ceiling", value: 6400, si_unit: "m", note: "About 21,000 feet" },
    ],
  },
  {
    slug: "concorde",
    name: "Concorde",
    subtitle: "The supersonic passenger jet that made the future feel real",
    category_id: "aircraft",
    description:
      "Concorde was a joint British-French supersonic marvel that flew passengers across the Atlantic at Mach 2.04, cutting the New York to London trip to about 3.5 hours. At cruise altitude, passengers could see the curvature of the Earth and the aircraft's nose would reach temperatures over 120 degrees Celsius. It entered service in 1976 and retired in 2003, and the world has been stuck in subsonic economy class ever since.",
    search_terms: "concorde|supersonic|sst|british airways|air france|mach 2",
    featured: 1,
    measurements: [
      { dimension: "length", label: "Overall length", value: 62.2, si_unit: "m" },
      { dimension: "length", label: "Wingspan", value: 25.6, si_unit: "m" },
      { dimension: "mass", label: "Operating empty mass", value: 78700, si_unit: "kg" },
      { dimension: "speed", label: "Maximum cruise speed", value: 603, si_unit: "m/s", note: "Mach 2.04, about 2,170 km/h" },
      { dimension: "length", label: "Cruise altitude", value: 18300, si_unit: "m", note: "About 60,000 feet" },
      { dimension: "length", label: "Range", value: 7250000, si_unit: "m", note: "7,250 km" },
      { dimension: "length", label: "Height", value: 12.2, si_unit: "m" },
      { dimension: "volume", label: "Fuel capacity", value: 119.5, si_unit: "m³", note: "119,500 liters" },
    ],
  },

  // ── Ships & Boats ────────────────────────────────────────────────────────

  {
    slug: "titanic",
    name: "RMS Titanic",
    subtitle: "The 'unsinkable' ship that sank on its maiden voyage",
    category_id: "ships",
    description:
      "The RMS Titanic was the largest ship afloat when it launched in 1912, a floating palace with a grand staircase, squash court, and Turkish bath. It struck an iceberg on April 14, 1912, and sank in under three hours, taking over 1,500 lives. The wreck sits 3,800 meters deep in the North Atlantic, which as it turns out is a much harder tourist destination to reach than anyone budgeted for.",
    search_terms: "titanic|rms titanic|white star line|unsinkable|ocean liner|iceberg",
    featured: 1,
    measurements: [
      { dimension: "length", label: "Overall length", value: 269, si_unit: "m" },
      { dimension: "mass", label: "Displacement", value: 46328000, si_unit: "kg", note: "About 46,328 tonnes" },
      { dimension: "length", label: "Height (keel to top of funnels)", value: 53, si_unit: "m" },
      { dimension: "length", label: "Beam (width)", value: 28.2, si_unit: "m" },
      { dimension: "speed", label: "Top speed", value: 11.8, si_unit: "m/s", note: "About 23 knots" },
      { dimension: "power", label: "Engine power", value: 36000000, si_unit: "W", note: "About 46,000 hp from steam engines and turbine" },
      { dimension: "length", label: "Wreck depth", value: 3800, si_unit: "m" },
    ],
  },
  {
    slug: "uss-gerald-ford",
    name: "Aircraft Carrier USS Gerald R. Ford (CVN-78)",
    subtitle: "The most expensive and advanced warship ever built",
    category_id: "ships",
    description:
      "The USS Gerald R. Ford cost approximately $13 billion and is the most expensive warship ever constructed. It is a floating city with a crew of over 4,500 people, two nuclear reactors, and an electromagnetic aircraft launch system that replaced the old steam catapults. The flight deck is so large you could fit three football fields on it, and the ship is designed to operate for 50 years without refueling its reactors.",
    search_terms: "aircraft carrier|uss ford|cvn-78|navy|carrier|supercarrier|nuclear",
    featured: 1,
    measurements: [
      { dimension: "length", label: "Overall length", value: 337, si_unit: "m" },
      { dimension: "mass", label: "Full load displacement", value: 100000000, si_unit: "kg", note: "About 100,000 tonnes" },
      { dimension: "speed", label: "Top speed", value: 15.4, si_unit: "m/s", note: "30+ knots" },
      { dimension: "area", label: "Flight deck area", value: 18000, si_unit: "m²" },
      { dimension: "power", label: "Reactor power output", value: 700000000, si_unit: "W", note: "Two A1B nuclear reactors" },
      { dimension: "length", label: "Beam (width at waterline)", value: 41, si_unit: "m" },
      { dimension: "length", label: "Height (keel to mast)", value: 76, si_unit: "m" },
    ],
  },
  {
    slug: "ever-given-container-ship",
    name: "Container Ship Ever Given",
    subtitle: "The ship that blocked the Suez Canal and broke global trade",
    category_id: "ships",
    description:
      "The Ever Given is a Golden-class container ship that became world-famous in March 2021 when it ran aground and blocked the Suez Canal for six days, holding up an estimated $9.6 billion in trade per day. At 400 meters long, it is one of the largest container ships ever built. The incident proved that the entire global economy can be brought to its knees by a single ship, some wind, and a bad day.",
    search_terms: "ever given|evergreen|container ship|suez canal|cargo ship",
    featured: 1,
    measurements: [
      { dimension: "length", label: "Overall length", value: 400, si_unit: "m" },
      { dimension: "mass", label: "Deadweight tonnage", value: 220000000, si_unit: "kg", note: "About 220,000 DWT" },
      { dimension: "length", label: "Beam (width)", value: 59, si_unit: "m" },
      { dimension: "speed", label: "Service speed", value: 12.9, si_unit: "m/s", note: "About 25 knots" },
      { dimension: "volume", label: "Container capacity", value: 42000, si_unit: "m³", note: "20,124 TEU; each TEU is about 33 m³ internal volume" },
      { dimension: "length", label: "Draft (depth below waterline)", value: 16, si_unit: "m" },
      { dimension: "length", label: "Height (keel to top)", value: 65, si_unit: "m" },
    ],
  },
  {
    slug: "kayak-standard",
    name: "Kayak (Standard Recreational)",
    subtitle: "A small human-powered boat for one",
    category_id: "ships",
    description:
      "The recreational kayak is perhaps the most intimate form of watercraft: just you, a paddle, some water, and occasionally a surprised duck. Modern recreational kayaks are made from rotomolded polyethylene and are designed for calm lakes and slow rivers. They are the opposite of an aircraft carrier in almost every measurable way, which makes the comparison deeply satisfying.",
    search_terms: "kayak|canoe|paddle|small boat|recreational boat",
    featured: 0,
    measurements: [
      { dimension: "length", label: "Overall length", value: 3.5, si_unit: "m" },
      { dimension: "mass", label: "Hull mass", value: 20, si_unit: "kg" },
      { dimension: "length", label: "Beam (width)", value: 0.66, si_unit: "m" },
      { dimension: "length", label: "Depth (hull height)", value: 0.33, si_unit: "m" },
      { dimension: "mass", label: "Max payload capacity", value: 115, si_unit: "kg" },
      { dimension: "speed", label: "Average paddling speed", value: 1.5, si_unit: "m/s", note: "About 5.4 km/h for a recreational paddler" },
    ],
  },

  // ── Trains & Rail ────────────────────────────────────────────────────────

  {
    slug: "shinkansen-n700",
    name: "Bullet Train (Shinkansen N700)",
    subtitle: "Japan's high-speed rail marvel",
    category_id: "trains",
    description:
      "The Shinkansen N700 series operates on Japan's Tokaido and Sanyo lines at speeds up to 300 km/h, carrying over 1,300 passengers in a full 16-car set. Since the first Shinkansen launched in 1964, there has never been a single passenger fatality due to derailment or collision. The train is so punctual that the average delay across all services is measured in seconds, not minutes.",
    search_terms: "shinkansen|bullet train|n700|japan rail|high speed rail|japanese train",
    featured: 1,
    measurements: [
      { dimension: "length", label: "Full train set length (16 cars)", value: 404, si_unit: "m" },
      { dimension: "mass", label: "Total train mass", value: 700000, si_unit: "kg" },
      { dimension: "speed", label: "Maximum operating speed", value: 83, si_unit: "m/s", note: "300 km/h" },
      { dimension: "power", label: "Total traction power", value: 17000000, si_unit: "W", note: "17 MW" },
      { dimension: "length", label: "Car width", value: 3.36, si_unit: "m" },
      { dimension: "length", label: "Car height", value: 3.6, si_unit: "m" },
      { dimension: "length", label: "Individual car length", value: 25, si_unit: "m" },
    ],
  },
  {
    slug: "freight-train-average",
    name: "Freight Train (Average)",
    subtitle: "The workhorses that haul the world's goods by rail",
    category_id: "trains",
    description:
      "An average North American freight train stretches roughly 2 kilometers and can carry the equivalent of 300 or more truckloads of cargo. Modern trains are so fuel-efficient they can move one ton of freight nearly 800 kilometers on a single gallon of diesel. They are slow, enormous, and unstoppable in the most literal sense: a fully loaded freight train needs over 2 kilometers to come to a complete stop.",
    search_terms: "freight train|cargo train|railroad|locomotive|rail freight",
    featured: 0,
    measurements: [
      { dimension: "length", label: "Typical train length", value: 2000, si_unit: "m", note: "About 100-120 cars" },
      { dimension: "mass", label: "Gross trailing tonnage", value: 10000000, si_unit: "kg", note: "About 10,000 tonnes" },
      { dimension: "speed", label: "Average speed", value: 22, si_unit: "m/s", note: "About 80 km/h" },
      { dimension: "length", label: "Stopping distance at speed", value: 2400, si_unit: "m", note: "At full load and speed" },
      { dimension: "power", label: "Locomotive power (typical x3)", value: 9000000, si_unit: "W", note: "Three 4,400 hp locomotives" },
      { dimension: "mass", label: "Single locomotive mass", value: 195000, si_unit: "kg" },
    ],
  },
  {
    slug: "shanghai-maglev",
    name: "Shanghai Maglev",
    subtitle: "The fastest commercial train in regular service",
    category_id: "trains",
    description:
      "The Shanghai Maglev connects Pudong International Airport to the city at a top speed of 431 km/h, making it the fastest commercial train service in the world. It uses magnetic levitation to float about 10 millimeters above the guideway, eliminating wheel friction entirely. The 30-kilometer trip takes just over 7 minutes, which is less time than most people spend trying to find their boarding pass.",
    search_terms: "maglev|shanghai|magnetic levitation|fastest train|transrapid",
    featured: 1,
    measurements: [
      { dimension: "speed", label: "Maximum operating speed", value: 120, si_unit: "m/s", note: "431 km/h in regular service" },
      { dimension: "length", label: "Single car length", value: 24, si_unit: "m" },
      { dimension: "mass", label: "Vehicle mass (single car)", value: 42000, si_unit: "kg" },
      { dimension: "length", label: "Levitation gap", value: 0.01, si_unit: "m", note: "10 mm magnetic gap" },
      { dimension: "length", label: "Track length", value: 30500, si_unit: "m", note: "30.5 km from airport to Longyang Road" },
      { dimension: "time", label: "Trip duration", value: 450, si_unit: "s", note: "About 7 minutes 30 seconds" },
    ],
  },

  // ── Spacecraft ───────────────────────────────────────────────────────────

  {
    slug: "space-shuttle",
    name: "Space Shuttle",
    subtitle: "NASA's reusable orbiter that defined an era of spaceflight",
    category_id: "spacecraft",
    description:
      "The Space Shuttle was the world's first reusable crewed spacecraft, flying 135 missions between 1981 and 2011. The full stack consisted of the orbiter, two solid rocket boosters, and an external fuel tank that together produced more thrust at liftoff than a million sports cars. It deployed the Hubble Space Telescope, built the International Space Station, and proved that landing a spacecraft on a runway like a glider is entirely possible, if somewhat terrifying.",
    search_terms: "space shuttle|shuttle|orbiter|nasa|sts|columbia|discovery|atlantis|endeavour",
    featured: 1,
    measurements: [
      { dimension: "length", label: "Overall height (full stack)", value: 56.1, si_unit: "m" },
      { dimension: "mass", label: "Launch mass (full stack)", value: 2030000, si_unit: "kg" },
      { dimension: "speed", label: "Orbital velocity", value: 7777, si_unit: "m/s", note: "About 28,000 km/h" },
      { dimension: "volume", label: "Payload bay volume", value: 300, si_unit: "m³" },
      { dimension: "force", label: "Total liftoff thrust", value: 30160000, si_unit: "N", note: "Combined SSMEs and SRBs" },
      { dimension: "length", label: "Orbiter length", value: 37.2, si_unit: "m" },
      { dimension: "length", label: "Orbiter wingspan", value: 23.8, si_unit: "m" },
      { dimension: "mass", label: "Orbiter empty mass", value: 68585, si_unit: "kg" },
    ],
  },
  {
    slug: "falcon-heavy",
    name: "Falcon Heavy",
    subtitle: "SpaceX's heavy-lift launcher and the most powerful operational rocket",
    category_id: "spacecraft",
    description:
      "The Falcon Heavy is essentially three Falcon 9 rockets bolted together, producing over 22 meganewtons of thrust at liftoff. Its inaugural flight in 2018 famously launched Elon Musk's personal Tesla Roadster into a heliocentric orbit with a mannequin named Starman at the wheel. With the ability to land all three boosters for reuse, it delivers heavy payloads to orbit at a fraction of the cost of its competitors.",
    search_terms: "falcon heavy|spacex|heavy lift|rocket|elon musk|starman",
    featured: 1,
    measurements: [
      { dimension: "length", label: "Height", value: 70, si_unit: "m" },
      { dimension: "mass", label: "Launch mass", value: 1420788, si_unit: "kg" },
      { dimension: "force", label: "Liftoff thrust", value: 22819000, si_unit: "N", note: "27 Merlin 1D engines total" },
      { dimension: "mass", label: "Payload to LEO", value: 63800, si_unit: "kg" },
      { dimension: "length", label: "Fairing diameter", value: 5.2, si_unit: "m" },
      { dimension: "mass", label: "Payload to Mars", value: 16800, si_unit: "kg" },
      { dimension: "length", label: "Core booster width", value: 3.66, si_unit: "m" },
    ],
  },
  {
    slug: "international-space-station",
    name: "International Space Station (ISS)",
    subtitle: "The largest structure ever built in space",
    category_id: "spacecraft",
    description:
      "The ISS is a habitable artificial satellite the size of a football field that has been continuously occupied since November 2000. It orbits Earth every 90 minutes at about 7,660 m/s, meaning the crew sees 16 sunrises and sunsets every day. Built by five space agencies and 15 countries at a cost exceeding $150 billion, it is the most expensive single object ever constructed by humans.",
    search_terms: "iss|space station|international space station|orbital|nasa|esa|roscosmos",
    featured: 1,
    measurements: [
      { dimension: "length", label: "Truss length", value: 109, si_unit: "m" },
      { dimension: "mass", label: "Total mass", value: 420000, si_unit: "kg" },
      { dimension: "speed", label: "Orbital velocity", value: 7660, si_unit: "m/s", note: "About 27,600 km/h" },
      { dimension: "volume", label: "Pressurized volume", value: 916, si_unit: "m³" },
      { dimension: "area", label: "Solar array area", value: 2500, si_unit: "m²" },
      { dimension: "power", label: "Solar array power output", value: 240000, si_unit: "W", note: "240 kW peak" },
      { dimension: "length", label: "Orbital altitude", value: 408000, si_unit: "m", note: "About 408 km" },
      { dimension: "length", label: "Module length (end to end)", value: 73, si_unit: "m" },
    ],
  },
  {
    slug: "voyager-1",
    name: "Voyager 1",
    subtitle: "The most distant human-made object in existence",
    category_id: "spacecraft",
    description:
      "Launched in 1977, Voyager 1 has been traveling away from Earth for over 48 years and is now in interstellar space, more than 24 billion kilometers from home. It carries a Golden Record containing sounds and images of Earth for any extraterrestrial civilization that might find it. The probe's radio signal, traveling at the speed of light, takes over 22 hours to reach Earth, and its transmitter has less power than a refrigerator light bulb.",
    search_terms: "voyager|voyager 1|interstellar|golden record|deep space|jpl|nasa probe",
    featured: 1,
    measurements: [
      { dimension: "mass", label: "Spacecraft mass", value: 825, si_unit: "kg" },
      { dimension: "speed", label: "Heliocentric velocity", value: 17000, si_unit: "m/s", note: "About 61,200 km/h" },
      { dimension: "length", label: "Distance from Earth", value: 24000000000000, si_unit: "m", note: "About 24 billion km; growing daily" },
      { dimension: "power", label: "Current RTG power output", value: 250, si_unit: "W", note: "Down from 470W at launch; decreasing ~4W per year" },
      { dimension: "data", label: "Data transmitted per hour", value: 72000, si_unit: "bytes", note: "20 bytes/s (160 bps) sustained over one hour" },
      { dimension: "length", label: "High-gain antenna diameter", value: 3.66, si_unit: "m" },
      { dimension: "time", label: "One-way light time to Earth", value: 80000, si_unit: "s", note: "About 22 hours" },
    ],
  },
  {
    slug: "apollo-lunar-module",
    name: "Apollo Lunar Module",
    subtitle: "The spindly spacecraft that landed humans on the Moon",
    category_id: "spacecraft",
    description:
      "The Apollo Lunar Module was the first crewed spacecraft designed to operate exclusively in the vacuum of space, with no need for aerodynamic shaping. It looked like a giant metallic insect wrapped in gold foil, and its walls were so thin you could poke a screwdriver through them. Despite looking like it was held together with tape and optimism, it successfully landed twelve astronauts on the lunar surface across six missions.",
    search_terms: "lunar module|lm|apollo|moon lander|grumman|eagle",
    featured: 0,
    measurements: [
      { dimension: "length", label: "Height", value: 7.0, si_unit: "m" },
      { dimension: "mass", label: "Total mass (fueled)", value: 15200, si_unit: "kg" },
      { dimension: "force", label: "Descent engine thrust", value: 45040, si_unit: "N", note: "Throttleable from 10% to 60%" },
      { dimension: "length", label: "Width (across landing gear)", value: 9.4, si_unit: "m" },
      { dimension: "volume", label: "Crew cabin volume", value: 6.65, si_unit: "m³" },
      { dimension: "force", label: "Ascent engine thrust", value: 15600, si_unit: "N" },
      { dimension: "mass", label: "Ascent stage dry mass", value: 2150, si_unit: "kg" },
      { dimension: "mass", label: "Descent stage dry mass", value: 2034, si_unit: "kg" },
    ],
  },
];
